@server = http://localhost:4005
@me = Authorization: Basic {{$processEnv USER}}:

GET {{server}}/odata/v4/action/Actions

### ---- GET ACTIONS ---------------------------------------------------
GET {{server}}/odata/v4/action/Actions

### ---- GET ACTIONS ---------------------------------------------------
GET {{server}}/odata/v4/action/getDataActionByName(name='name')

### ---- CREATE DATA ACTION  ---------------------------------------------------
POST {{server}}/odata/v4/action/createDataAction
Content-Type: application/json;IEEE754Compatible=true

{
  "action": {
    "name": "name",
    "description": "description",
    "userAction": false,
    "type": "D"
  },
  "definition": {
    "service": "http://localhost:4006/odata/v4/test",
    "entity": "/Vehicles",
    "rules": [{
      "field": "stock",
      "operator": "equals",
      "value": "1"
    }]
  }
}

